# Generated by Django 5.2.6 on 2025-11-18 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_create_default_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(default='🏆', max_length=50)),
                ('xp_recompensa', models.IntegerField(default=0)),
                ('condicao_tipo', models.CharField(choices=[('pontos_totais', 'Pontos Totais'), ('rodadas_completas', 'Rodadas Completas'), ('tema_completo', 'Tema Completo'), ('nivel_atingido', 'Nível Atingido')], default='pontos_totais', max_length=50)),
                ('condicao_valor', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
                'ordering': ['condicao_valor'],
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='titulo',
            field=models.CharField(blank=True, default='Iniciante', max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='xp_total',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ConquistaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desbloqueada_em', models.DateTimeField(auto_now_add=True)),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='quiz.conquista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conquista do Usuário',
                'verbose_name_plural': 'Conquistas dos Usuários',
                'ordering': ['-desbloqueada_em'],
                'unique_together': {('usuario', 'conquista')},
            },
        ),
    ]
