# Generated by Django 5.2.8 on 2025-11-25 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_conquista_perfilusuario_nivel_perfilusuario_titulo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizIAHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200)),
                ('pontuacao', models.IntegerField(default=0)),
                ('total_perguntas', models.IntegerField(default=15)),
                ('respostas_corretas', models.IntegerField(default=0)),
                ('percentual_acertos', models.IntegerField(default=0)),
                ('concluido_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz IA - Histórico',
                'verbose_name_plural': 'Quiz IA - Históricos',
                'ordering': ['-concluido_em'],
            },
        ),
    ]
