# Generated by Django 5.2.7 on 2025-12-08 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiziahistorico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('professor', 'Professor')], default='aluno', max_length=10, verbose_name='Tipo de Usuário'),
        ),
        migrations.CreateModel(
            name='SessaoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_sessao', models.DateTimeField(auto_now_add=True)),
                ('fim_sessao', models.DateTimeField(blank=True, null=True)),
                ('tempo_total_segundos', models.IntegerField(default=0)),
                ('perguntas_respondidas', models.IntegerField(default=0)),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='quiz.tema')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_jogo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Jogo',
                'verbose_name_plural': 'Sessões de Jogo',
                'ordering': ['-inicio_sessao'],
            },
        ),
        migrations.CreateModel(
            name='EstatisticaProgresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('total_perguntas_respondidas', models.IntegerField(default=0)),
                ('total_perguntas_corretas', models.IntegerField(default=0)),
                ('percentual_acerto', models.FloatField(default=0.0)),
                ('tempo_total_jogo_segundos', models.IntegerField(default=0)),
                ('xp_total', models.IntegerField(default=0)),
                ('nivel_atual', models.IntegerField(default=1)),
                ('rodadas_completas', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas_progresso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estatística de Progresso',
                'verbose_name_plural': 'Estatísticas de Progresso',
                'ordering': ['-data_registro'],
                'indexes': [models.Index(fields=['usuario', '-data_registro'], name='quiz_estati_usuario_4b48ff_idx')],
            },
        ),
    ]
