# Generated by Django 5.2.7 on 2025-12-11 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_perfilusuario_tipo_usuario_sessaojogo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_personalizado', models.CharField(max_length=200, verbose_name='Tema Personalizado')),
                ('pin', models.CharField(max_length=6, unique=True, verbose_name='PIN da Sala')),
                ('ativa', models.BooleanField(default=True, verbose_name='Sala Ativa')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('alternativa_a', models.CharField(max_length=500)),
                ('alternativa_b', models.CharField(max_length=500)),
                ('alternativa_c', models.CharField(max_length=500)),
                ('alternativa_d', models.CharField(max_length=500)),
                ('resposta_correta', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem da pergunta no quiz')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='quiz.sala')),
            ],
            options={
                'verbose_name': 'Pergunta da Sala',
                'verbose_name_plural': 'Perguntas da Sala',
                'ordering': ['sala', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='AlunoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrou_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_acesso', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='quiz.sala')),
            ],
            options={
                'verbose_name': 'Aluno na Sala',
                'verbose_name_plural': 'Alunos nas Salas',
                'ordering': ['-entrou_em'],
                'unique_together': {('sala', 'aluno')},
            },
        ),
    ]
