# Generated by Django 5.2.7 on 2025-12-12 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_sala_perguntasala_alunosala'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perguntas_respondidas', models.IntegerField(default=0)),
                ('perguntas_corretas', models.IntegerField(default=0)),
                ('pontuacao_total', models.IntegerField(default=0)),
                ('quiz_completo', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos_sala', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='quiz.sala')),
            ],
            options={
                'verbose_name': 'Progresso na Sala',
                'verbose_name_plural': 'Progressos nas Salas',
                'ordering': ['-atualizado_em'],
                'unique_together': {('aluno', 'sala')},
            },
        ),
        migrations.CreateModel(
            name='RespostaSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_escolhida', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('correta', models.BooleanField(default=False)),
                ('pontuacao', models.IntegerField(default=0)),
                ('respondida_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_sala', to=settings.AUTH_USER_MODEL)),
                ('pergunta_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='quiz.perguntasala')),
                ('progresso_sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='quiz.progressosala')),
            ],
            options={
                'verbose_name': 'Resposta na Sala',
                'verbose_name_plural': 'Respostas nas Salas',
                'ordering': ['-respondida_em'],
                'unique_together': {('aluno', 'pergunta_sala')},
            },
        ),
    ]
